# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_mpsBART3_log_dmvn', PACKAGE = 'mpsBART3', x, Sigma)
}

sum_exclude_col <- function(mat, exclude_int) {
    .Call('_mpsBART3_sum_exclude_col', PACKAGE = 'mpsBART3', mat, exclude_int)
}

bspline <- function(x, x_obs) {
    .Call('_mpsBART3_bspline', PACKAGE = 'mpsBART3', x, x_obs)
}

sbart <- function(x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a, sample_tau_b) {
    .Call('_mpsBART3_sbart', PACKAGE = 'mpsBART3', x_train, y_train, x_test, B_train, B_test, D, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump, a, sample_tau_b)
}

mat_init <- function(n) {
    .Call('_mpsBART3_mat_init', PACKAGE = 'mpsBART3', n)
}

vec_init <- function(n) {
    .Call('_mpsBART3_vec_init', PACKAGE = 'mpsBART3', n)
}

std_inv <- function(A, diag) {
    .Call('_mpsBART3_std_inv', PACKAGE = 'mpsBART3', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_mpsBART3_std_pinv', PACKAGE = 'mpsBART3', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_mpsBART3_faster_simple_std_inv', PACKAGE = 'mpsBART3', A, diag)
}

faster_std_inv <- function(A, diag) {
    .Call('_mpsBART3_faster_std_inv', PACKAGE = 'mpsBART3', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_mpsBART3_rMVN2', PACKAGE = 'mpsBART3', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_mpsBART3_rMVNslow', PACKAGE = 'mpsBART3', b, Q)
}

matrix_mat <- function(array) {
    .Call('_mpsBART3_matrix_mat', PACKAGE = 'mpsBART3', array)
}

rand_unif <- function() {
    .Call('_mpsBART3_rand_unif', PACKAGE = 'mpsBART3')
}

